<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Postalcode;


class PostalcodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('postalcodes')->insert([
            [ //1
                'cpcouid' => 'ES',
                'cptownm' => 'GASTEIZ',
                'cptownmori' => 'GASTEIZ',
                'cpstrpcori' => '01001',
                'cpendpcori' => '01001',
                'cpstrpc' => '01001',
                'cpendpc' => '01001',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '54893',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //2
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA',
                'cptownmori' => 'VITORIA',
                'cpstrpcori' => '01001',
                'cpendpcori' => '01001',
                'cpstrpc' => '01001',
                'cpendpc' => '01001',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '54893',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //3
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA-GASTEIZ',
                'cptownmori' => 'VITORIA-GASTEIZ',
                'cpstrpcori' => '01001',
                'cpendpcori' => '01001',
                'cpstrpc' => '01001',
                'cpendpc' => '01001',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '54893',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [ //4
                'cpcouid' => 'ES',
                'cptownm' => 'GASTEIZ',
                'cptownmori' => 'GASTEIZ',
                'cpstrpcori' => '01002',
                'cpendpcori' => '01002',
                'cpstrpc' => '01002',
                'cpendpc' => '01002',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56760',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //5
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA',
                'cptownmori' => 'VITORIA',
                'cpstrpcori' => '01002',
                'cpendpcori' => '01002',
                'cpstrpc' => '01002',
                'cpendpc' => '01002',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56760',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //6
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA-GASTEIZ',
                'cptownmori' => 'VITORIA-GASTEIZ',
                'cpstrpcori' => '01002',
                'cpendpcori' => '01002',
                'cpstrpc' => '01002',
                'cpendpc' => '01002',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56760',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [ //7
                'cpcouid' => 'ES',
                'cptownm' => 'GASTEIZ',
                'cptownmori' => 'GASTEIZ',
                'cpstrpcori' => '01003',
                'cpendpcori' => '01003',
                'cpstrpc' => '01003',
                'cpendpc' => '01003',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56761',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //8
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA',
                'cptownmori' => 'VITORIA',
                'cpstrpcori' => '01003',
                'cpendpcori' => '01003',
                'cpstrpc' => '01003',
                'cpendpc' => '01003',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56761',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //9
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA-GASTEIZ',
                'cptownmori' => 'VITORIA-GASTEIZ',
                'cpstrpcori' => '01003',
                'cpendpcori' => '01003',
                'cpstrpc' => '01003',
                'cpendpc' => '01003',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56761',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [ //10
                'cpcouid' => 'ES',
                'cptownm' => 'GASTEIZ',
                'cptownmori' => 'GASTEIZ',
                'cpstrpcori' => '01004',
                'cpendpcori' => '01004',
                'cpstrpc' => '01004',
                'cpendpc' => '01004',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56762',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //11
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA',
                'cptownmori' => 'VITORIA',
                'cpstrpcori' => '01004',
                'cpendpcori' => '01004',
                'cpstrpc' => '01004',
                'cpendpc' => '01004',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56762',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //12
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA-GASTEIZ',
                'cptownmori' => 'VITORIA-GASTEIZ',
                'cpstrpcori' => '01004',
                'cpendpcori' => '01004',
                'cpstrpc' => '01004',
                'cpendpc' => '01004',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56762',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],

            [ //13
                'cpcouid' => 'ES',
                'cptownm' => 'GASTEIZ',
                'cptownmori' => 'GASTEIZ',
                'cpstrpcori' => '01005',
                'cpendpcori' => '01005',
                'cpstrpc' => '01005',
                'cpendpc' => '01005',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56762',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //14
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA',
                'cptownmori' => 'VITORIA',
                'cpstrpcori' => '01005',
                'cpendpcori' => '01005',
                'cpstrpc' => '01005',
                'cpendpc' => '01005',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56762',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //15
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA-GASTEIZ',
                'cptownmori' => 'VITORIA-GASTEIZ',
                'cpstrpcori' => '01005',
                'cpendpcori' => '01005',
                'cpstrpc' => '01005',
                'cpendpc' => '01005',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56762',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],

            [ //16
                'cpcouid' => 'ES',
                'cptownm' => 'GASTEIZ',
                'cptownmori' => 'GASTEIZ',
                'cpstrpcori' => '01006',
                'cpendpcori' => '01006',
                'cpstrpc' => '01006',
                'cpendpc' => '01006',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '57575',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //17
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA',
                'cptownmori' => 'VITORIA',
                'cpstrpcori' => '01006',
                'cpendpcori' => '01006',
                'cpstrpc' => '01006',
                'cpendpc' => '01006',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '57575',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //18
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA-GASTEIZ',
                'cptownmori' => 'VITORIA-GASTEIZ',
                'cpstrpcori' => '01006',
                'cpendpcori' => '01006',
                'cpstrpc' => '01006',
                'cpendpc' => '01006',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '57575',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [ //19
                'cpcouid' => 'ES',
                'cptownm' => 'ARMENTIA',
                'cptownmori' => 'ARMENTIA',
                'cpstrpcori' => '01007',
                'cpendpcori' => '01007',
                'cpstrpc' => '01007',
                'cpendpc' => '01007',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '03239',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [ //20
                'cpcouid' => 'ES',
                'cptownm' => 'GASTEIZ',
                'cptownmori' => 'GASTEIZ',
                'cpstrpcori' => '01007',
                'cpendpcori' => '01007',
                'cpstrpc' => '01007',
                'cpendpc' => '01007',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56668',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //21
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA',
                'cptownmori' => 'VITORIA',
                'cpstrpcori' => '01007',
                'cpendpcori' => '01007',
                'cpstrpc' => '01007',
                'cpendpc' => '01007',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56668',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //22
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA-GASTEIZ',
                'cptownmori' => 'VITORIA-GASTEIZ',
                'cpstrpcori' => '01007',
                'cpendpcori' => '01007',
                'cpstrpc' => '01007',
                'cpendpc' => '01007',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '56668',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [ //23
                'cpcouid' => 'ES',
                'cptownm' => 'GASTEIZ',
                'cptownmori' => 'GASTEIZ',
                'cpstrpcori' => '01008',
                'cpendpcori' => '01008',
                'cpstrpc' => '01008',
                'cpendpc' => '01008',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '54893',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //24
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA',
                'cptownmori' => 'VITORIA',
                'cpstrpcori' => '01008',
                'cpendpcori' => '01008',
                'cpstrpc' => '01008',
                'cpendpc' => '01008',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '54893',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //25
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA-GASTEIZ',
                'cptownmori' => 'VITORIA-GASTEIZ',
                'cpstrpcori' => '01008',
                'cpendpcori' => '01008',
                'cpstrpc' => '01008',
                'cpendpc' => '01008',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '54893',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [ //26
                'cpcouid' => 'ES',
                'cptownm' => 'GASTEIZ',
                'cptownmori' => 'GASTEIZ',
                'cpstrpcori' => '01009',
                'cpendpcori' => '01009',
                'cpstrpc' => '01009',
                'cpendpc' => '01009',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '54893',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //27
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA',
                'cptownmori' => 'VITORIA',
                'cpstrpcori' => '01009',
                'cpendpcori' => '01009',
                'cpstrpc' => '01009',
                'cpendpc' => '01009',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '54893',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //28
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA-GASTEIZ',
                'cptownmori' => 'VITORIA-GASTEIZ',
                'cpstrpcori' => '01009',
                'cpendpcori' => '01009',
                'cpstrpc' => '01009',
                'cpendpc' => '01009',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '54893',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [ //29
                'cpcouid' => 'ES',
                'cptownm' => 'ALI',
                'cptownmori' => 'ALI',
                'cpstrpcori' => '01010',
                'cpendpcori' => '01010',
                'cpstrpc' => '01010',
                'cpendpc' => '01010',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '57207',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [ //30
                'cpcouid' => 'ES',
                'cptownm' => 'EHARI',
                'cptownmori' => 'EHARI',
                'cpstrpcori' => '01010',
                'cpendpcori' => '01010',
                'cpstrpc' => '01010',
                'cpendpc' => '01010',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '17925',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [ //31
                'cpcouid' => 'ES',
                'cptownm' => 'GASTEIZ',
                'cptownmori' => 'GASTEIZ',
                'cpstrpcori' => '01010',
                'cpendpcori' => '01010',
                'cpstrpc' => '01010',
                'cpendpc' => '01010',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '54893',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //32
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA',
                'cptownmori' => 'VITORIA',
                'cpstrpcori' => '01010',
                'cpendpcori' => '01010',
                'cpstrpc' => '01010',
                'cpendpc' => '01010',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '54893',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [ //33
                'cpcouid' => 'ES',
                'cptownm' => 'VITORIA-GASTEIZ',
                'cptownmori' => 'VITORIA-GASTEIZ',
                'cpstrpcori' => '01010',
                'cpendpcori' => '01010',
                'cpstrpc' => '01010',
                'cpendpc' => '01010',
                'cpprvid' => 'VI',
                'cpprvcod' => '',
                'cpprvnom' => 'ALAVA',
                'cptownpcode' => '54893',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46001',
                'cpendpcori' => '46001',
                'cpstrpc' => '46001',
                'cpendpc' => '46001',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46002',
                'cpendpcori' => '46002',
                'cpstrpc' => '46002',
                'cpendpc' => '46002',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46003',
                'cpendpcori' => '46003',
                'cpstrpc' => '46003',
                'cpendpc' => '46003',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46004',
                'cpendpcori' => '46004',
                'cpstrpc' => '46004',
                'cpendpc' => '46004',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46005',
                'cpendpcori' => '46005',
                'cpstrpc' => '46005',
                'cpendpc' => '46005',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46006',
                'cpendpcori' => '46006',
                'cpstrpc' => '46006',
                'cpendpc' => '46006',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46007',
                'cpendpcori' => '46007',
                'cpstrpc' => '46007',
                'cpendpc' => '46007',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46008',
                'cpendpcori' => '46008',
                'cpstrpc' => '46008',
                'cpendpc' => '46008',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46009',
                'cpendpcori' => '46009',
                'cpstrpc' => '46009',
                'cpendpc' => '46009',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46010',
                'cpendpcori' => '46010',
                'cpstrpc' => '46010',
                'cpendpc' => '46010',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46011',
                'cpendpcori' => '46011',
                'cpstrpc' => '46011',
                'cpendpc' => '46011',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46012',
                'cpendpcori' => '46012',
                'cpstrpc' => '46012',
                'cpendpc' => '46012',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46013',
                'cpendpcori' => '46013',
                'cpstrpc' => '46013',
                'cpendpc' => '46013',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46014',
                'cpendpcori' => '46014',
                'cpstrpc' => '46014',
                'cpendpc' => '46014',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46015',
                'cpendpcori' => '46015',
                'cpstrpc' => '46015',
                'cpendpc' => '46015',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46016',
                'cpendpcori' => '46016',
                'cpstrpc' => '46016',
                'cpendpc' => '46016',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46017',
                'cpendpcori' => '46017',
                'cpstrpc' => '46017',
                'cpendpc' => '46017',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46018',
                'cpendpcori' => '46018',
                'cpstrpc' => '46018',
                'cpendpc' => '46018',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46019',
                'cpendpcori' => '46019',
                'cpstrpc' => '46019',
                'cpendpc' => '46019',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46020',
                'cpendpcori' => '46020',
                'cpstrpc' => '46020',
                'cpendpc' => '46020',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46021',
                'cpendpcori' => '46021',
                'cpstrpc' => '46021',
                'cpendpc' => '46021',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46022',
                'cpendpcori' => '46022',
                'cpstrpc' => '46022',
                'cpendpc' => '46022',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46023',
                'cpendpcori' => '46023',
                'cpstrpc' => '46023',
                'cpendpc' => '46023',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46024',
                'cpendpcori' => '46024',
                'cpstrpc' => '46024',
                'cpendpc' => '46024',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46025',
                'cpendpcori' => '46025',
                'cpstrpc' => '46025',
                'cpendpc' => '46025',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '50815',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'VALENCIA',
                'cptownmori' => 'VALENCIA',
                'cpstrpcori' => '46026',
                'cpendpcori' => '46026',
                'cpstrpc' => '46026',
                'cpendpc' => '46026',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '55666',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'ARGUIJO',
                'cptownmori' => 'ARGUIJO',
                'cpstrpcori' => '42169',
                'cpendpcori' => '42169',
                'cpstrpc' => '42169',
                'cpendpc' => '42169',
                'cpprvid' => 'SO',
                'cpprvcod' => '',
                'cpprvnom' => 'SORIA',
                'cptownpcode' => '03110',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
             [
                'cpcouid' => 'ES',
                'cptownm' => 'VALLONGA. DE (PARTIDA)',
                'cptownmori' => 'VALLONGA, DE (PARTIDA)',
                'cpstrpcori' => '03113',
                'cpendpcori' => '03113',
                'cpstrpc' => '03113',
                'cpendpc' => '03113',
                'cpprvid' => 'ALC',
                'cpprvcod' => '',
                'cpprvnom' => 'ALICANTE',
                'cptownpcode' => '51148',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'TORRETA. LA',
                'cptownmori' => 'TORRETA. LA',
                'cpstrpcori' => '03110',
                'cpendpcori' => '03110',
                'cpstrpc' => '03110',
                'cpendpc' => '03110',
                'cpprvid' => 'A',
                'cpprvcod' => '',
                'cpprvnom' => 'ALICANTE',
                'cptownpcode' => '49362',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'RIBARROJA DE TURIA',
                'cptownmori' => 'RIBARROJA DE TURIA',
                'cpstrpcori' => '46190',
                'cpendpcori' => '46190',
                'cpstrpc' => '46190',
                'cpendpc' => '46190',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '41082',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'BARCELONA',
                'cptownmori' => 'BARCELONA',
                'cpstrpcori' => '08039',
                'cpendpcori' => '08039',
                'cpstrpc' => '08039',
                'cpendpc' => '08039',
                'cpprvid' => 'B',
                'cpprvcod' => '',
                'cpprvnom' => 'BARCELONA',
                'cptownpcode' => '04599',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'NOVELDA',
                'cptownmori' => 'NOVELDA',
                'cpstrpcori' => '03660',
                'cpendpcori' => '03660',
                'cpstrpc' => '03660',
                'cpendpc' => '03660',
                'cpprvid' => 'A',
                'cpprvcod' => '',
                'cpprvnom' => 'ALICANTE',
                'cptownpcode' => '32267',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'CASTELLON DE LA PLANA',
                'cptownmori' => 'CASTELLON DE LA PLANA',
                'cpstrpcori' => '12100',
                'cpendpcori' => '12100',
                'cpstrpc' => '12100',
                'cpendpc' => '12100',
                'cpprvid' => 'C',
                'cpprvcod' => '',
                'cpprvnom' => 'CASTELLON',
                'cptownpcode' => '12499',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'ELDA',
                'cptownmori' => 'ELDA',
                'cpstrpcori' => '03600',
                'cpendpcori' => '03600',
                'cpstrpc' => '03600',
                'cpendpc' => '03600',
                'cpprvid' => 'A',
                'cpprvcod' => '',
                'cpprvnom' => 'ALICANTE',
                'cptownpcode' => '18061',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'SANT JOAN DE MORO',
                'cptownmori' => 'SANT JOAN DE MORO',
                'cpstrpcori' => '12130',
                'cpendpcori' => '12130',
                'cpstrpc' => '12130',
                'cpendpc' => '12130',
                'cpprvid' => 'C',
                'cpprvcod' => '',
                'cpprvnom' => 'CASTELLON',
                'cptownpcode' => '44669',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'LEGANES',
                'cptownmori' => 'LEGANES',
                'cpstrpcori' => '28918',
                'cpendpcori' => '28918',
                'cpstrpc' => '28918',
                'cpendpc' => '28918',
                'cpprvid' => 'M',
                'cpprvcod' => '',
                'cpprvnom' => 'MADRID',
                'cptownpcode' => '26144',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'ALAQUAS',
                'cptownmori' => 'ALAQUAS',
                'cpstrpcori' => '46970',
                'cpendpcori' => '46970',
                'cpstrpc' => '46970',
                'cpendpc' => '46970',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '00902',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'FOIOS',
                'cptownmori' => 'FOIOS',
                'cpstrpcori' => '46134',
                'cpendpcori' => '46134',
                'cpstrpc' => '46134',
                'cpendpc' => '46134',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '20078',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'PETRES',
                'cptownmori' => 'PETRES',
                'cpstrpcori' => '46501',
                'cpendpcori' => '46501',
                'cpstrpc' => '46501',
                'cpendpc' => '46501',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '56592',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'ALGECIRAS',
                'cptownmori' => 'ALGECIRAS',
                'cpstrpcori' => '11201',
                'cpendpcori' => '11201',
                'cpstrpc' => '11201',
                'cpendpc' => '11201',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '01600',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'FAURA',
                'cptownmori' => 'FAURA',
                'cpstrpcori' => '46512',
                'cpendpcori' => '46512',
                'cpstrpc' => '46512',
                'cpendpc' => '46512',
                'cpprvid' => 'V',
                'cpprvcod' => '',
                'cpprvnom' => 'VALENCIA',
                'cptownpcode' => '19476',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'ALMENARA',
                'cptownmori' => 'ALMENARA',
                'cpstrpcori' => '12590',
                'cpendpcori' => '12590',
                'cpstrpc' => '12590',
                'cpendpc' => '12590',
                'cpprvid' => 'C',
                'cpprvcod' => '',
                'cpprvnom' => 'CASTELLON',
                'cptownpcode' => '01799',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'MOLINA DE SEGURA',
                'cptownmori' => 'MOLINA DE SEGURA',
                'cpstrpcori' => '30500',
                'cpendpcori' => '30500',
                'cpstrpc' => '30500',
                'cpendpc' => '30500',
                'cpprvid' => 'MU',
                'cpprvcod' => '',
                'cpprvnom' => 'MURCIA',
                'cptownpcode' => '30008',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'ALCAYNA',
                'cptownmori' => 'ALCAYNA',
                'cpstrpcori' => '30500',
                'cpendpcori' => '30500',
                'cpstrpc' => '30500',
                'cpendpc' => '30500',
                'cpprvid' => 'MU',
                'cpprvcod' => '',
                'cpprvnom' => 'MURCIA',
                'cptownpcode' => '01161',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'ES',
                'cptownm' => 'PORRINO',
                'cptownmori' => 'PORRINO',
                'cpstrpcori' => '36400',
                'cpendpcori' => '36400',
                'cpstrpc' => '36400',
                'cpendpc' => '36400',
                'cpprvid' => 'PO',
                'cpprvcod' => '',
                'cpprvnom' => 'PONTEVEDRA',
                'cptownpcode' => '60508',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'FR',
                'cptownm' => 'PERPIGNAN',
                'cptownmori' => 'PERPIGNAN',
                'cpstrpcori' => '66000',
                'cpendpcori' => '66059',
                'cpstrpc' => '66000',
                'cpendpc' => '66059',
                'cpprvid' => '',
                'cpprvcod' => '',
                'cpprvnom' => '',
                'cptownpcode' => '28875',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'FR',
                'cptownm' => 'ROQUES',
                'cptownmori' => 'ROQUES',
                'cpstrpcori' => '31120',
                'cpendpcori' => '31120',
                'cpstrpc' => '31120',
                'cpendpc' => '31120',
                'cpprvid' => '',
                'cpprvcod' => '',
                'cpprvnom' => '',
                'cptownpcode' => '13050',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'FR',
                'cptownm' => 'TOULUSE',
                'cptownmori' => 'TOULUSE',
                'cpstrpcori' => '31000',
                'cpendpcori' => '31099',
                'cpstrpc' => '31000',
                'cpendpc' => '31099',
                'cpprvid' => '',
                'cpprvcod' => '',
                'cpprvnom' => '',
                'cptownpcode' => '13147',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],[
                'cpcouid' => 'PT',
                'cptownm' => 'MATOSINHOS',
                'cptownmori' => 'MATOSINHOS',
                'cpstrpcori' => '4450-204',
                'cpendpcori' => '4450-204',
                'cpstrpc' => '4450-204',
                'cpendpc' => '4450-204',
                'cpprvid' => '11',
                'cpprvcod' => '',
                'cpprvnom' => 'PORTO',
                'cptownpcode' => '11990',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'DE',
                'cptownm' => 'COLOGNE',
                'cptownmori' => 'COLOGNE',
                'cpstrpcori' => '50400',
                'cpendpcori' => '50400',
                'cpstrpc' => '50400',
                'cpendpc' => '50400',
                'cpprvid' => '10',
                'cpprvcod' => '',
                'cpprvnom' => 'NORDRHEIN-WESTFALEN',
                'cptownpcode' => '11990',
                'cptownplace' => 'N',
                'cpaliasin' => 'Y',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'DE',
                'cptownm' => 'KOELN',
                'cptownmori' => 'KOELN',
                'cpstrpcori' => '50400',
                'cpendpcori' => '50400',
                'cpstrpc' => '50400',
                'cpendpc' => '50400',
                'cpprvid' => '10',
                'cpprvcod' => '',
                'cpprvnom' => 'NORDRHEIN-WESTFALEN',
                'cptownpcode' => '11990',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'IT',
                'cptownm' => 'MOMPANTERO',
                'cptownmori' => 'MOMPANTERO',
                'cpstrpcori' => '10059',
                'cpendpcori' => '10059',
                'cpstrpc' => '10059',
                'cpendpc' => '10059',
                'cpprvid' => '083',
                'cpprvcod' => 'TO',
                'cpprvnom' => 'TORINO',
                'cptownpcode' => '07297',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'IT',
                'cptownm' => 'SUSA',
                'cptownmori' => 'SUSA',
                'cpstrpcori' => '10059',
                'cpendpcori' => '10059',
                'cpstrpc' => '10059',
                'cpendpc' => '10059',
                'cpprvid' => '083',
                'cpprvcod' => 'TO',
                'cpprvnom' => 'TORINO',
                'cptownpcode' => '12898',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
            [
                'cpcouid' => 'IT',
                'cptownm' => 'BRUZOLO',
                'cptownmori' => 'BRUZOLO',
                'cpstrpcori' => '10050',
                'cpendpcori' => '10050',
                'cpstrpc' => '10050',
                'cpendpc' => '10050',
                'cpprvid' => '083',
                'cpprvcod' => 'TO',
                'cpprvnom' => 'TORINO',
                'cptownpcode' => '01631',
                'cptownplace' => 'N',
                'cpaliasin' => 'N',
                'cpbaja' => '',
            ],
        ]);
    }
}
